### ISSUE TITLE
crawler.py not working

### ISSUE THREAD

**Issue by MannDude** [Revertron/wyrd#10]
You say:

Run:
`python3 src/crawler.py`

However MySQLdb is not compatible with Python 3.

So you get the error:

```
python3 src/crawler.py
Traceback (most recent call last):
  File "src/crawler.py", line 8, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'
```

I changed mysqldb to "mysqlclient", etc, and still doesn't work.

Then went back to the original script and tried:

`python2 src/crawler.py`

Used python2 instead of 3 to see if it'd work with mysqldb, and that fails too:

```
python2 src/crawler.py
Traceback (most recent call last):
  File "src/crawler.py", line 19, in <module>
    from queue import Queue
ImportError: No module named queue
```

Though that time it made it further in the script before giving errors.

**Comment by Revertron** [comment]
I believe, that `MySQLdb` is installed by command `pip install mysqlclient`. Can you try and bring back the results?

**Comment by MannDude** [comment]
> Requirement` already satisfied: mysqlclient in /usr/lib/python2.7/dist-packages (1.3.7)

The error persists:

```
$ python3 src/crawler.py  
Traceback (most recent call last):
  File "src/crawler.py", line 8, in <module>
    import MySQLdb
ImportError: No module named 'MySQLdb'
```

I have confirmed that the MySQL service is running. I may attempt a clean install and go from there, this isn't the first time this box has had strange dependency issues. May just backup important things and start with a clean slate.
