### ISSUE TITLE
Couple errors when running.

### ISSUE THREAD

**Issue by Incognify** [Revertron/wyrd#11]
Hello, when running the script via 'python3 src/crawler.py' I encounter the error(s) below. I believe I have met all dependency requirements. I can confirm that the database and user has been made with the proper permissions and that the contents of /wyrd/bind has been moved to /etc/bind/ as per instructions. 

```
    Traceback (most recent call last):
      File "src/crawler.py", line 92, in doRequest
        ygg.connect(host_port)
    ConnectionRefusedError: [Errno 111] Connection refused
    selfInfo: None 
     
    Traceback (most recent call last):
      File "src/crawler.py", line 451, in <module>
        crawl()
      File "src/crawler.py", line 395, in crawl
        for k,v in selfInfo['response']['self'].items():
    TypeError: 'NoneType' object is not subscriptable
```

**Comment by Revertron** [comment]
Hi, @Incognify! You need to enable connections to the running Yggdrasil service (in yggdrasil.conf) like this:
```
AdminListen: tcp://127.0.0.1:9001
```

**Comment by Incognify** [comment]
Hi, thank you. Is this the expected result when running the script now?

It seems to slowly be adding these in my terminal but when I view the wyrd database in phpmyadmin it still shows no tables.

![Screenshot_2020-12-16_11-50-19](https://user-images.githubusercontent.com/75774592/102379728-29dda280-3f95-11eb-9f7d-5d9e6a67b2a2.png)

**Comment by Revertron** [comment]
The tables must be created before running script, and it will insert data to the DB after it crawled whole network.

**Comment by Incognify** [comment]
Thank you. I will let it continue to run.

When it completes is there anything special I need to do at that point to access .ygg domains? I am confused as to where I add the servers:


Server IP | Location
-- | --
301:2522::53 | Praha, Czechia
301:2923::53 | Bratislava, Slovakia
300:4523::53 | Duesseldorf, Germany
303:8b1a::53 | Saint Petersburg, Russia


Do those need to be my peers in my yggdrasil.conf file? Added elsewhere? Sorry for the newb questions.

**Comment by Revertron** [comment]
You don't need to run the crawler if you just want to use my servers :)
But if you want to use your own DNS server that will be able to resolve .ygg domains, you need to use crawler :)

**Comment by Incognify** [comment]
I see. I created a .ygg domain and it's on a remote server. I see the domain in your domain.sql file.. On my local box I want to be able to access it, that is what I am trying to achieve. :) 

I'm a bit confused but I think I'm making progress.
